# Generated by Django 6.0.4 on 2026-07-28 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('monto_donado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_donacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('meta_horas', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador ONG'), ('VOLUNTARIO', 'Voluntario')], default='VOLUNTARIO', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('habilidades', models.CharField(blank=True, help_text='Ej: Logística, Primeros Auxilios, Enseñar', max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('lugar', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('habilidad_requerida', models.CharField(max_length=100)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='gestion.programasocial')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=100)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('asistio', models.BooleanField(default=False)),
                ('horas_registradas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('codigo_qr_token', models.CharField(blank=True, max_length=100, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='gestion.actividad')),
                ('voluntario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='gestion.perfilusuario')),
            ],
        ),
    ]
