# Generated by Django 6.0.4 on 2026-07-29 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('habilidades', models.CharField(help_text='Ej: Primeros auxilios, Docencia', max_length=200)),
                ('horas_aportadas', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='turnoapoyo',
            old_name='fin',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='turnoapoyo',
            old_name='inicio',
            new_name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='habilidad_requerida',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='programasocial',
            name='meta_horas',
        ),
        migrations.RemoveField(
            model_name='turnoapoyo',
            name='codigo_qr_token',
        ),
        migrations.RemoveField(
            model_name='turnoapoyo',
            name='horas_registradas',
        ),
        migrations.RemoveField(
            model_name='turnoapoyo',
            name='tarea',
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programasocial',
            name='meta_beneficiarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='lugar',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.programasocial'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='monto_donado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='donante',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='turnoapoyo',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.actividad'),
        ),
        migrations.AlterField(
            model_name='turnoapoyo',
            name='voluntario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.voluntario'),
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
