# Generated by Django 6.0.4 on 2026-07-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_voluntario_rename_titulo_actividad_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='email',
            field=models.EmailField(default='contacto@donante.com', max_length=254),
        ),
    ]
